# Site title and subtitle. This is used in _includes/header.html
title: 'Taco Help'
subtitle: 'Knowledge base for tacoapp.com, purveyors of fine productivity.'

product_name: 'Taco'

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'https://tacoapp.com/'

# Default categories (in order) to appear in the navigation
sections: [
    ['how-it-works', 'How Taco Works'],
    ['connectors', 'Connectors'],
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
pygments: true

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

markdown: kramdown
